# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       NODE_ENV: development
#       DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
#     volumes:
#       - .:/usr/src/app
#     command: npm run dev

#   db:
#     image: postgres:14
#     container_name: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     volumes:
#       - db:/var/lib/postgresql/data

# volumes:
#   db:


version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
