version: '3.8'

services:
  app:
    build:
      context: ../  # Cambiado al directorio raíz del proyecto
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env  # Ajusta la ruta para apuntar al archivo .env en el directorio raíz
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: postgres:14
    env_file:
      - ../.env  # Ajusta la ruta para apuntar al archivo .env en el directorio raíz
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
